### ISSUE TITLE
Utility function to count number of rows in all database tables

### ISSUE THREAD

**Issue by grigory93** [teradata-aster-field/toaster#50]
Such function would come very handy for preliminary database analysis. It may also count number of columns. Possible name could would be `getTableCounts`.

**Comment by briankreeger** [comment]
Option for grouping by schema would nice.

**Comment by grigory93** [comment]
@kreegerlabs do you mean including multiple schemas?

**Comment by grigory93** [comment]
TODO: add parallel feature.
