### ISSUE TITLE
createClusterPairsPlot is not compatible with new version of GGally (ggpairs)

### ISSUE THREAD

**Issue by grigory93** [teradata-aster-field/toaster#62]
Latest release of GGally (1.0.1) changed argument formats and function behavior.

**Comment by Htimstrebor** [comment]
Can you confirm this is the ticket that will include all clusters regardless of how small the cluster is and will be adding input columns to select for viewing as well?

**Comment by grigory93** [comment]
No, this is different. It deals with the changes in **GGally** package and already has been fixed in the build you saw (and probably have).
