### ISSUE TITLE
Better sampling and ability to filter features in createClusterPairsPlot

### ISSUE THREAD

**Issue by Htimstrebor** [teradata-aster-field/toaster#63]
1. Not able to see all clusters. Small clusters are hidden.
2. Discussion of adding input columns to select for viewing. 

These were the issues we discussed a few weeks ago. Thank you.

**Comment by grigory93** [comment]
1. to see all clusters will utilize conditional sampling with stratum column _clusterid_.
2. will add both _include_ and _except_ filter arguments

**Comment by grigory93** [comment]
After checking _createClusterPairsPlot_ I determined that it works as follows:
1. _computeClusterSample_ does make conditional sampling using cluster id
2. _createClusterPairsPlot_ uses all data points from the sample.

Please check that the sample obtained in step 1. indeed contains all clusters when you run it and let me know of the results.

**Comment by grigory93** [comment]
Created #64 to address the problem of missing clusters in the sample when one or more clusters are significantly smaller.
